allowBuilds:
  sharp: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  '@prisma/engines': true
  prisma: true
overrides:
  vue: 3.5.40
minimumReleaseAgeExclude:
  - '@prisma/adapter-mariadb@7.9.1'
  - '@prisma/client-runtime-utils@7.9.1'
  - '@prisma/client@7.9.1'
  - '@prisma/debug@7.9.1'
  - '@prisma/driver-adapter-utils@7.9.1'
  - '@tiptap/core@3.29.1'
  - '@tiptap/extension-blockquote@3.29.1'
  - '@tiptap/extension-bold@3.29.1'
  - '@tiptap/extension-bubble-menu@3.29.1'
  - '@tiptap/extension-bullet-list@3.29.1'
  - '@tiptap/extension-code-block@3.29.1'
  - '@tiptap/extension-code@3.29.1'
  - '@tiptap/extension-document@3.29.1'
  - '@tiptap/extension-dropcursor@3.29.1'
  - '@tiptap/extension-floating-menu@3.29.1'
  - '@tiptap/extension-gapcursor@3.29.1'
  - '@tiptap/extension-hard-break@3.29.1'
  - '@tiptap/extension-heading@3.29.1'
  - '@tiptap/extension-horizontal-rule@3.29.1'
  - '@tiptap/extension-italic@3.29.1'
  - '@tiptap/extension-link@3.29.1'
  - '@tiptap/extension-list-item@3.29.1'
  - '@tiptap/extension-list-keymap@3.29.1'
  - '@tiptap/extension-list@3.29.1'
  - '@tiptap/extension-ordered-list@3.29.1'
  - '@tiptap/extension-paragraph@3.29.1'
  - '@tiptap/extension-strike@3.29.1'
  - '@tiptap/extension-text@3.29.1'
  - '@tiptap/extension-underline@3.29.1'
  - '@tiptap/extensions@3.29.1'
  - '@tiptap/pm@3.29.1'
  - '@tiptap/starter-kit@3.29.1'
  - '@tiptap/vue-3@3.29.1'
  - '@nuxt/kit@3.21.10'
  - '@nuxt/test-utils@4.1.0'
  - '@prisma/config@7.9.1'
  - '@prisma/dev@0.24.17'
  - '@prisma/engines@7.9.1'
  - '@prisma/fetch-engine@7.9.1'
  - '@prisma/get-platform@7.9.1'
  - prisma@7.9.1
