import { z } from 'zod'
import { externalUrlSchema, jsonStringArraySchema, relativeUrlSchema, richTextSchema, slugSchema } from './common'

const displayStatus = z.enum(['ENABLED', 'DISABLED'])
const contentStatus = z.enum(['DRAFT', 'PUBLISHED', 'DISABLED'])

export const companySchema = z.object({
  companyName: z.string().trim().min(1).max(200), shortName: z.string().trim().max(100).optional().nullable(), slogan: z.string().trim().max(255).optional().nullable(),
  logo: relativeUrlSchema, favicon: relativeUrlSchema, heroTitle: z.string().trim().max(255).optional().nullable(), heroSubtitle: z.string().trim().max(1000).optional().nullable(),
  introduction: z.string().max(20_000).optional().nullable(), fullDescription: richTextSchema, businessScope: richTextSchema, advantages: jsonStringArraySchema.optional().nullable(),
  address: z.string().trim().max(500).optional().nullable(), phone: z.string().trim().max(64).optional().nullable(), email: z.string().trim().email().max(254).optional().nullable(),
  wechat: z.string().trim().max(128).optional().nullable(), whatsapp: z.string().trim().max(128).optional().nullable(), workingHours: z.string().trim().max(255).optional().nullable(),
  latitude: z.coerce.number().min(-90).max(90).optional().nullable(), longitude: z.coerce.number().min(-180).max(180).optional().nullable(), registrationInfo: z.string().trim().max(500).optional().nullable()
})

export const siteSettingSchema = z.object({
  siteName: z.string().trim().min(1).max(200), siteUrl: externalUrlSchema, siteTitle: z.string().trim().max(255).optional().nullable(), siteKeywords: z.string().trim().max(500).optional().nullable(),
  siteDescription: z.string().max(10_000).optional().nullable(), logo: relativeUrlSchema, favicon: relativeUrlSchema, footerText: z.string().max(10_000).optional().nullable(),
  copyright: z.string().trim().max(500).optional().nullable(), icpNumber: z.string().trim().max(100).optional().nullable(),
  themeConfig: z.record(z.string(), z.unknown()).optional().nullable(), socialLinks: z.array(z.object({ name: z.string().max(64), url: externalUrlSchema })).max(20).optional().nullable(),
  contactConfig: z.record(z.string(), z.unknown()).optional().nullable()
})

export const categorySchema = z.object({ name: z.string().trim().min(1).max(150), slug: slugSchema, parentId: z.coerce.number().int().positive().optional().nullable(), summary: z.string().max(10_000).optional().nullable(), description: richTextSchema, coverImage: relativeUrlSchema, icon: z.string().trim().max(255).optional().nullable(), sortOrder: z.coerce.number().int().min(-100000).max(100000).default(0), status: displayStatus.default('ENABLED'), seoTitle: z.string().trim().max(255).optional().nullable(), seoKeywords: z.string().trim().max(500).optional().nullable(), seoDescription: z.string().max(10_000).optional().nullable() })

const specificationSchema = z.array(z.object({ group: z.string().trim().min(1).max(100), items: z.array(z.object({ label: z.string().trim().min(1).max(100), value: z.string().trim().min(1).max(1000) })).min(1).max(100) })).max(50)
export const productSchema = z.object({ categoryId: z.coerce.number().int().positive(), name: z.string().trim().min(1).max(200), slug: slugSchema, model: z.string().trim().max(150).optional().nullable(), subtitle: z.string().trim().max(500).optional().nullable(), summary: z.string().max(10_000).optional().nullable(), description: richTextSchema, coverImage: relativeUrlSchema, videoUrl: externalUrlSchema, features: jsonStringArraySchema.optional().nullable(), applications: jsonStringArraySchema.optional().nullable(), specifications: specificationSchema.optional().nullable(), sortOrder: z.coerce.number().int().min(-100000).max(100000).default(0), isFeatured: z.boolean().default(false), status: contentStatus.default('DRAFT'), seoTitle: z.string().trim().max(255).optional().nullable(), seoKeywords: z.string().trim().max(500).optional().nullable(), seoDescription: z.string().max(10_000).optional().nullable(), imageIds: z.array(z.coerce.number().int().positive()).max(50).optional() })

export const partnerSchema = z.object({ name: z.string().trim().min(1).max(200), slug: slugSchema, logo: relativeUrlSchema, coverImage: relativeUrlSchema, summary: z.string().max(10_000).optional().nullable(), description: richTextSchema, website: externalUrlSchema, cooperationType: z.string().trim().max(100).optional().nullable(), sortOrder: z.coerce.number().int().min(-100000).max(100000).default(0), isFeatured: z.boolean().default(false), status: displayStatus.default('ENABLED'), seoTitle: z.string().trim().max(255).optional().nullable(), seoDescription: z.string().max(10_000).optional().nullable() })
export const serviceSchema = z.object({ name: z.string().trim().min(1).max(200), slug: slugSchema, icon: z.string().trim().max(255).optional().nullable(), coverImage: relativeUrlSchema, summary: z.string().max(10_000).optional().nullable(), description: richTextSchema, features: jsonStringArraySchema.optional().nullable(), processSteps: z.array(z.object({ title: z.string().trim().min(1).max(200), description: z.string().trim().max(1000).optional() })).max(30).optional().nullable(), sortOrder: z.coerce.number().int().min(-100000).max(100000).default(0), isFeatured: z.boolean().default(false), status: displayStatus.default('ENABLED'), seoTitle: z.string().trim().max(255).optional().nullable(), seoDescription: z.string().max(10_000).optional().nullable() })
export const bannerSchema = z.object({ title: z.string().trim().min(1).max(255), subtitle: z.string().trim().max(1000).optional().nullable(), image: relativeUrlSchema, mobileImage: relativeUrlSchema, buttonText: z.string().trim().max(100).optional().nullable(), buttonLink: z.string().trim().max(1024).refine(value => value.startsWith('/') || /^https?:\/\//i.test(value), '链接必须是站内路径或 HTTP(S) 地址').optional().nullable(), position: z.string().trim().min(1).max(64).default('HOME_HERO'), sortOrder: z.coerce.number().int().min(-100000).max(100000).default(0), status: displayStatus.default('ENABLED'), startAt: z.coerce.date().optional().nullable(), endAt: z.coerce.date().optional().nullable() }).refine(value => !value.startAt || !value.endAt || value.startAt <= value.endAt, '结束时间必须晚于开始时间')
export const articleSchema = z.object({ title: z.string().trim().min(1).max(255), slug: slugSchema, summary: z.string().max(10_000).optional().nullable(), content: richTextSchema, coverImage: relativeUrlSchema, author: z.string().trim().max(100).optional().nullable(), status: contentStatus.default('DRAFT'), isFeatured: z.boolean().default(false), sortOrder: z.coerce.number().int().min(-100000).max(100000).default(0), seoTitle: z.string().trim().max(255).optional().nullable(), seoKeywords: z.string().trim().max(500).optional().nullable(), seoDescription: z.string().max(10_000).optional().nullable(), publishedAt: z.coerce.date().optional().nullable() })
export const messageSchema = z.object({ status: z.enum(['NEW', 'PROCESSING', 'RESOLVED', 'SPAM']), adminRemark: z.string().max(10_000).optional().nullable() })
export const userSchema = z.object({ username: z.string().trim().min(3).max(64).regex(/^[a-zA-Z0-9_.-]+$/), password: z.string().min(12).max(128).optional(), displayName: z.string().trim().min(1).max(100), email: z.string().trim().email().max(254).optional().nullable(), avatar: relativeUrlSchema, role: z.enum(['SUPER_ADMIN', 'EDITOR']).default('EDITOR'), status: z.enum(['ENABLED', 'DISABLED']).default('ENABLED') })
